FROM node:22-alpine as build
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev git > /dev/null 2>&1
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

# Database
ARG DATABASE_HOST
ARG DATABASE_PORT=5432
ARG DATABASE_CLIENT=postgres
ARG DATABASE_NAME=podcastmanager
ARG DATABASE_USERNAME=podcastmanager_user
ARG DATABASE_PASSWORD
ARG DATABASE_SSL=false

ENV DATABASE_CLIENT=$DATABASE_CLIENT
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_SSL=$DATABASE_SSL

# AWS
ARG USE_TEST_BUCKET=true
ARG AWS_ACCESS_KEY_ID
ARG AWS_ACCESS_SECRET
ARG AWS_REGION=eu-central-1
ARG AWS_BUCKET=podcast-manager
ARG AWS_BUCKET_TEST=strapi-cffc-test

ENV USE_TEST_BUCKET=$USE_TEST_BUCKET
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET
ENV AWS_REGION=$AWS_REGION
ENV AWS_BUCKET=$AWS_BUCKET
ENV AWS_BUCKET_TEST=$AWS_BUCKET_TEST

# Strapi
ARG APP_KEYS
ARG API_TOKEN_SALT
ARG ADMIN_JWT_SECRET
ARG TRANSFER_TOKEN_SALT

ENV APP_KEYS=$APP_KEYS
ENV API_TOKEN_SALT=$API_TOKEN_SALT
ENV ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET
ENV TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT

# Bind to all interfaces (override at runtime via Coolify env).
# NOTE: $HOSTNAME is not available to ENV expansion during build and would
# resolve to an empty string here, which crashes `strapi build`.
ENV HOST=0.0.0.0

WORKDIR /opt/
# The repo is managed with pnpm (see pnpm-lock.yaml); corepack picks up the
# pinned version from package.json > packageManager.
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile
ENV PATH=/opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY . .
RUN npm run build

# Slim the installed dependencies down to production-only ones for the runtime stage
RUN cd /opt && pnpm prune --prod

# Creating final production image
FROM node:22-alpine
RUN apk add --no-cache vips-dev
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

# Database
ARG DATABASE_HOST
ARG DATABASE_PORT=5432
ARG DATABASE_CLIENT=postgres
ARG DATABASE_NAME=podcastmanager
ARG DATABASE_USERNAME=podcastmanager_user
ARG DATABASE_PASSWORD
ARG DATABASE_SSL=false

ENV DATABASE_CLIENT=$DATABASE_CLIENT
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_SSL=$DATABASE_SSL

# AWS
ARG USE_TEST_BUCKET=true
ARG AWS_ACCESS_KEY_ID
ARG AWS_ACCESS_SECRET
ARG AWS_REGION=eu-central-1
ARG AWS_BUCKET=podcast-manager
ARG AWS_BUCKET_TEST=strapi-cffc-test

ENV USE_TEST_BUCKET=$USE_TEST_BUCKET
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET
ENV AWS_REGION=$AWS_REGION
ENV AWS_BUCKET=$AWS_BUCKET
ENV AWS_BUCKET_TEST=$AWS_BUCKET_TEST

# Strapi
ARG APP_KEYS
ARG API_TOKEN_SALT
ARG ADMIN_JWT_SECRET
ARG TRANSFER_TOKEN_SALT

ENV APP_KEYS=$APP_KEYS
ENV API_TOKEN_SALT=$API_TOKEN_SALT
ENV ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET
ENV TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT

# Bind to all interfaces (override at runtime via Coolify env).
ENV HOST=0.0.0.0

WORKDIR /opt/
COPY --from=build /opt/node_modules ./node_modules
WORKDIR /opt/app
COPY --from=build /opt/app ./
ENV PATH=/opt/node_modules/.bin:$PATH

RUN chown -R node:node /opt/app
USER node
CMD ["npm", "run", "start"]
