FROM node:20-alpine as build
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev git > /dev/null 2>&1
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

# Database
ARG DATABASE_HOST
ARG DATABASE_PORT=5432
ARG DATABASE_CLIENT=podcastmanager
ARG DATABASE_NAME=podcast
ARG DATABASE_USERNAME=podcastmanager_user
ARG DATABASE_PASSWORD
ARG DATABASE_SSL=false

ENV DATABASE_CLIENT=$DATABASE_CLIENT
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_SSL=$DATABASE_SSL

# AWS
ARG USE_TEST_BUCKET=true
ARG AWS_ACCESS_KEY_ID
ARG AWS_ACCESS_SECRET
ARG AWS_REGION=eu-central-1
ARG AWS_BUCKET=podcast-manager
ARG AWS_BUCKET_TEST=strapi-cffc-test

ENV USE_TEST_BUCKET=$USE_TEST_BUCKET
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET
ENV AWS_REGION=$AWS_REGION
ENV AWS_BUCKET=$AWS_BUCKET
ENV AWS_BUCKET_TEST=$AWS_BUCKET_TEST

# Set by coolify
ENV HOST=$HOSTNAME

WORKDIR /opt/
COPY projects/strapi/cffc-v4/package.json projects/strapi/cffc-v4/package-lock.json ./
RUN npm install -g node-gyp
RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install --only=production
ENV PATH=/opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY ./projects/strapi/cffc-v4 .
RUN npm run build

# Creating final production image
FROM node:20-alpine
RUN apk add --no-cache vips-dev
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

# Database
ARG DATABASE_HOST
ARG DATABASE_PORT=5432
ARG DATABASE_CLIENT=podcastmanager
ARG DATABASE_NAME=podcast
ARG DATABASE_USERNAME=podcastmanager_user
ARG DATABASE_PASSWORD
ARG DATABASE_SSL=false

ENV DATABASE_CLIENT=$DATABASE_CLIENT
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_SSL=$DATABASE_SSL

# AWS
ARG USE_TEST_BUCKET=true
ARG AWS_ACCESS_KEY_ID
ARG AWS_ACCESS_SECRET
ARG AWS_REGION=eu-central-1
ARG AWS_BUCKET=podcast-manager
ARG AWS_BUCKET_TEST=strapi-cffc-test

ENV USE_TEST_BUCKET=$USE_TEST_BUCKET
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET
ENV AWS_REGION=$AWS_REGION
ENV AWS_BUCKET=$AWS_BUCKET
ENV AWS_BUCKET_TEST=$AWS_BUCKET_TEST

# Set by coolify
ENV HOST=$HOSTNAME

WORKDIR /opt/
COPY --from=build /opt/node_modules ./node_modules
WORKDIR /opt/app
COPY --from=build /opt/app ./
ENV PATH=/opt/node_modules/.bin:$PATH

RUN chown -R node:node /opt/app
USER node
CMD ["npm", "run", "start"]
